---
stages:
- name: DEPLOY
  inputs:
  - type: git
    branch: master
    service: ${REPO}
  triggers:
  - type: commit
  properties:
  - name: CLOUDANT_db
    value: ${CLOUDANT_db}
  - name: ADMIN_USERNAME
    value: ${ADMIN_USERNAME}
  - name: ADMIN_PASSWORD
    value: ${ADMIN_PASSWORD}
  - name: DOCKER_EXTRACTOR_NAME
    value: "l2fprod/darkvision-extractor-master"
  - name: OPENWHISK_API_HOST
    value: "openwhisk.ng.bluemix.net"
  - name: WATSON_API_KEY
    value: ${WATSON_API_KEY}
  - name: ALCHEMY_API_KEY
    value: ${ALCHEMY_API_KEY}
  - name: STT_CALLBACK_SECRET
    value: ASecret{{name}}4Dv
  jobs:
  - name: Deploy
    type: deployer
    target:
      region_id: ${REGION_ID}
      organization: ${ORG_NAME}
      space: ${SPACE_NAME}
      application: ${CF_APP_NAME}
    script: |-
      #!/bin/bash
      ./.bluemix/pipeline-DEPLOY.sh
